config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'event#index'
  get '/index', to: 'event#index'
  get '/show', to: 'event#show'


  # Authentication
  get '/register', to: 'users#new'
  post '/register', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  # User Profile
  get '/profile', to: 'users#show'

  # Text Confirmation
  get '/text', to: 'text#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event
  attr_reader :name, :image_url, :genre, :venue, :dates, :min_price, :max_price
  def initialize(data)
    @name = data[:name]
    @image_url = data[:image_url]
    @genre = data[:genre]
    @venue = data[:venue]
    @dates = [{date: data[:date], time: data[:time], url: data[:url]}]
    if data[:minPrice].class == Hash
      @min_price = data[:minPrice][:value].to_f
    else
      @min_price = data[:minPrice] || 0.0
    end
    @max_price = data[:maxPrice] || Float::MAX
  end

  def add_date(date, time, url)
    @dates << {date: date, time: time, url: url}
  end

  Months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
  def self.datify(datetime)
    date = datetime[:date].split('-')
    time = datetime[:time].split(':')
    "#{date[2]} #{Months[date[1].to_i - 1]}, #{date[0]} @ #{time[0]}:#{time[1]}"
  end
end

app/models/genre.rb
class GenreList
  attr_reader :genres

  def initialize(data)
    @genres = data[:genres]
  end
end

app/models/genre_list.rb
class GenreList
  attr_reader :genres

  def initialize(data)
    @genres = data[:name]
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates_presence_of :name, :role
  validates :email, presence: true, uniqueness: true

  enum role: [:default, :admin]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/entry_controller.rb
class EntryController < ApplicationController
  def index
  end
end

app/controllers/event_controller.rb
class EventController < ApplicationController
  def show
    bleh = {
      name: "Totally a Super Fake Event",
      url: 'www.chucktesta.com',
      genre: 'big mood',
      venue: 'dimmsdale dimmadome',
      date: {date: 'tuesay'},
      minPrice: 4,
      maxPrice: 45000
    }
    render locals: {n: 2, event: Event.new(bleh)}
  end

  def index
    render locals: {facade: EventFacade.new(params)}
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:success] = "Welcome, #{user.name}!"
      redirect_to '/profile'
    else
      flash[:error] = 'Wrong email and/or password. Please try again.'
      render :new
    end
  end

  def destroy
    reset_session
    flash[:success] = 'You are logged out.'
    redirect_to root_path
  end
end

app/controllers/text_controller.rb
class TextController < ApplicationController
  def show
  end

  def create
    event = Event.find(params[:event])
    message = "Your friend has invited you to see the play #{event.title} with them"
    Text.create(params[:phone_number], message)

    redirect_to '/show'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome, #{@user.name}! You are registered and logged in."
      redirect_to '/profile'
    else
      flash[:error] = @user.errors.full_messages.to_sentence
      render :new
    end
  end

  def show
  end

  private
  def user_params
    params.permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/entry/index.html.erb
<div class='screen-centered'>
  <%#<img src='https://lorempixel.com/400/800/nightlife' class='responsive-img' style='position: fixed; z-index: -999; width: 100%'>%>
  <img src='bg1.png' style='position: fixed; z-index: -999; height: 100%'>
  <%= form_tag('/index', method: :get) do %>
  <div class='col s12'>
  <div class='row'>
    <h4 style='color: #ffffff; text-shadow: -1px 0 black, 1px 0 black, 0 1px black, 0 -1px black, 2px 2px 0 #000000, 3px 4px 4px #000000'>Where ya at?</h4>
    <div class='z-depth-3' style='padding: 0 1rem 0 1rem; border: 1px solid white; border-radius: 1rem; background: white'>
      <div class='input-field'>
        <!-- <input  id='location' type='text' class='' style='margin: 0; background: white; color: black'> -->
        <!-- <label for='location' style='color: black'>Location</label> -->
        <%= label_tag :city %>
        <%= text_field_tag :city %>
      </div>
    </div>
  </div>
  <div class='row'>
    <!-- <a class='right waves-effect waves-light btn red' style='margin-right: 1rem'> -->
    <%= submit_tag 'Shows!' %>
  </div>
  </div>
  <% end %>
</div>

app/views/event/_show.html.erb
<div id='modal<%= n %>' class='modal bottom-sheet' style='height: 92.5vh; max-height: 100%'>
  <div style='height: 33.3%; width: 100%; position: relative; overflow: hidden'>
    <div class='screen-centered' style='background: black'>
      <img src='<%= event.image_url %>' style='height: 100%'>
    </div>
    <button class='modal-close btn' style='position: absolute; top: 0.912rem; left: 0.912rem'>Close</button>
    <h4 style='position: absolute; bottom: 0px; left: 0; margin-left: 0.912rem; color: #ffffff; text-shadow: -1px 0 black, 1px 0 black, 0 1px black, 0 -1px black, 2px 2px 0 #000000, 3px 4px 4px #000000'><%= event.name %></h4>
  </div>
  <div class='modal-content' style='background: white; height: 66.6%'>
    <div style=''>
      <h5 style='color: rgb(238, 110, 115)'><%= event.genre %></h5>
    </div>
    <div style='height: 2px; width: 100%; margins: 0 10%; background: black'></div>
    <div>
      <ul>
      <% event.dates.reverse.each do |date| %>
        <li style='margin-bottom: 1rem; padding: 0 1rem'><a href='<%= date[:url] %>' class='btn' style='width: 100%'><%= Event.datify(date) %></a></li>
      <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/event/index.html.erb
<div style='height: 5rem; width: 100%'></div>

<div class='events-container'>
  <div id='filter' class='filter-box'>
    <ul class='genre'>
      <%= form_tag '/index', method: :get do %>
        <%#= select_tag "genre", options_for_select(facade.genres)%>
        <div id="slider"></div>

        <label for=price-start" class='filter-text'>Price Start: </>
        <input id="price-start" name="minPrice" type="number" value="<%= facade.priceMin %>"/>
        <label for=price-start" class='filter-text'>Price End:</>
        <input id="price-end" name="maxPrice" type="number" value="<%= facade.priceMax %>" />

        <label for='date' class='filter-text'>Click for Calendar</>
        <input type="text" class="datepicker filter-text" id="date" name="date" value="<%= facade.date %>" />

        <%= submit_tag 'Filter', class: 'btn' %>
      <% end %>
    </ul>
  </div>

  <div class='col s12'>
  <% facade.events.each_with_index do |event, n| %>
    <div class='events-row'>
      <button class='modal-trigger' style='margins: 0; padding: 0; border: 0; width: 100%; background: transparent' data-target='modal<%= n %>'>
      <div class='z-depth-4 events-card' style='position: relative'>
        <div class='events-image-container screen-centered'>
            <%# <img src='https://lorempixel.com/100/200/nightlife' style='width: 100%'> %>
            <img src='<%= event.image_url %>' style='height: 100%'>
        </div>

        <div class='events-content-container'>
          <div class='title-box red lighten-2 events-title-box'>
            <h5 class='events-title'><%= event.name %></h5>
          </div>
          <div class='events-info-box'>
            <div class='events-info-text'>
              <%# <em class='events-genre'><%= event.genre %1></em> %>
              <em><%= event.genre %></em>
              <%#= event.date %>
            </div>
          </div>
        </div>
      </div>
    </button>
    </div>

    <%= render partial: 'show', locals: {event: event, n: n} %>
  <% end %>
  </div>
</div>

app/views/event/show.html.erb
<div style='height: 5rem; width: 100%'></div>
<button class='btn modal-trigger' data-target='modal<%= n %>'>Open</button>
<%= render partial: 'show', locals: {n: n, event: event} %>

<section>
  <%= form_tag '/text', method: :post do %>
    <%= hidden_field_tag 'event', event.id %>
    <%= label_tag 'friend', "Friend's phone number" %>
    <%= text_field_tag :friend %>
  <% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CheeksNSeats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href='https://fonts.googleapis.com/icon?family=Material+Icons' rel='stylesheet'>
    <meta name='viewport' content='width=device-width, initial-scale=1.0'/>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <img src='bg1.png' class='bg-image'>
    <nav class='z-depth-3' style='position: fixed; height: 7.5vh; z-index: 1003'>
      <a href='#' class='brand-logo left'>CnS</a>
      <ul id='nav-mobile' class='right'>
        <li><%= link_to 'Register', register_path, {class: 'navbar-link'} unless current_user %></li>
        <li><%= link_to 'Sign In', login_path, {class: 'navbar-link'} unless current_user %></li>
        <% if current_user %>
          <li><%= link_to 'Log Out', logout_path %></li>
          <li><%= link_to current_user.name, profile_path %></li>
        <% end %>
    </nav>

    <section class="flash-message">
      <% flash.each do |type, message| %>
        <p><%= message %></p>
      <% end %>
    </section>

    <%= yield %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/text/show.html.erb
<h2>Your text message has been sent!</h2>
<%= button_to 'Back to Play', '/show' %>

app/views/users/new.html.erb
<h1>Create an Account:</h1>

<%= form_tag('/register') do %>
  <%= label_tag :name %>
  <%= text_field_tag :name %>

  <%= label_tag :email %>
  <%= text_field_tag :email %>

  <%= label_tag :password %>
  <%= password_field_tag :password %>

  <%= submit_tag 'Register' %>
<% end %>